import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

interface SubmitFormData {
    name: string
    email: string
    mobilenumber: string
}


export async function getServerSideProps() {
    return { props: {} }
}

const Home: NextPage = () => {
    function SubmitForm(e: React.FormEvent<HTMLFormElement>) {
        e.preventDefault()
        const formdata = new FormData(e.currentTarget);
        const data: SubmitFormData = Array.from(formdata.entries()).reduce((memo: SubmitFormData, [key, value]: [string, string | File]) => ({
            ...memo,
            [key]: value,
        }), {} as SubmitFormData);
        console.log(data)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Form Submission</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Submit your data below
                </h1>
                <form className={styles.form} onSubmit={SubmitForm} method="post">
                    <div className={styles.group}>
                        <label htmlFor="name">Name:</label>
                        <input type="text" className={styles.input} id="name" name="name"/>
                    </div>
                    <div className={styles.group}>
                        <label htmlFor="email">Email:</label>
                        <input type="email" className={styles.input} id="email" name="email"/>
                    </div>
                    <div className={styles.group}>
                        <label htmlFor="mobilenumber">Mobile:</label>
                        <input type="tel" className={styles.input} id="mobilenumber" name="mobilenumber"/>
                    </div>
                    <button type="submit">Submit</button>
                </form>


            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
